package connectionprofiles

import (
	"bytes"
	"crypto/ecdh"
	"encoding/base64"
	"errors"

	"github.com/albertloky/SBXR/internal/state"
)

type QualificationFixture struct {
	xray, singBox []byte
	source        PublicationSource
	access        map[state.ClientAccessValue]string
}

func (QualificationFixture) String() string {
	return "Connection Profile qualification fixture: redacted"
}
func (QualificationFixture) GoString() string {
	return "Connection Profile qualification fixture: redacted"
}
func (fixture QualificationFixture) Configurations() ([]byte, []byte) {
	return append([]byte(nil), fixture.xray...), append([]byte(nil), fixture.singBox...)
}
func (fixture QualificationFixture) PublicationSource() PublicationSource { return fixture.source }
func (fixture QualificationFixture) ReadClientAccessValue(value state.ClientAccessValue) string {
	return fixture.access[value]
}

// NewQualificationFixture returns public, no-authority material generated by
// the same complete six-profile renderers used for reviewed Plans.
func NewQualificationFixture() (QualificationFixture, error) {
	private, err := ecdh.X25519().NewPrivateKey(bytes.Repeat([]byte{7}, 32))
	if err != nil {
		return QualificationFixture{}, err
	}
	reality, realityErr := NewRealityCredentials("11111111-1111-4111-8111-111111111111", base64.RawURLEncoding.EncodeToString(private.Bytes()), base64.RawURLEncoding.EncodeToString(private.PublicKey().Bytes()), "0123456789abcdef")
	xhttp, xhttpErr := NewXHTTPCredentials("22222222-2222-4222-8222-222222222222", "/2222222222222222222222222222222222222222222222222222222222222222")
	websocket, websocketErr := NewWebSocketCredentials("33333333-3333-4333-8333-333333333333", "/3333333333333333333333333333333333333333333333333333333333333333")
	hysteria2, hysteria2Err := NewHysteria2Credentials("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
	tuic, tuicErr := NewTUICCredentials("55555555-5555-4555-8555-555555555555", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
	anyTLS, anyTLSErr := NewAnyTLSCredentials("cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc")
	if errors.Join(realityErr, xhttpErr, websocketErr, hysteria2Err, tuicErr, anyTLSErr) != nil {
		return QualificationFixture{}, errors.New("qualification credentials unavailable")
	}
	directTLS := NewDirectTLSContribution(DirectTLSRequest{Revision: 1, DestinationIP: "192.0.2.10", Hostname: "direct.example.com", Hysteria2: DirectTLSConsumer{Port: 443, CertificatePointer: "/var/lib/sbxr/certificates/domain/current"}, TUIC: DirectTLSConsumer{Port: 8443, CertificatePointer: "/var/lib/sbxr/certificates/domain/current"}, AnyTLS: DirectTLSConsumer{Port: 9443, CertificatePointer: "/var/lib/sbxr/certificates/domain/current"}})
	request := RegistryViewRequest{
		ClientAddress: "192.0.2.10",
		Reality:       ViewRequest{Revision: 1, Enabled: true, Port: 443, Target: RealityTarget{Address: "edge.example.net:443", ServerName: "edge.example.net"}, Fingerprint: "chrome", XrayVersion: "v26.3.27", Credentials: reality},
		XHTTP:         XHTTPViewRequest{Revision: 1, Enabled: true, Hostname: "xhttp.example.com", OriginAddress: "127.0.0.1", OriginPort: 11080, Mode: state.XHTTPPacketUp, XrayVersion: "v26.3.27", Credentials: xhttp},
		WebSocket:     WebSocketViewRequest{Revision: 1, Enabled: true, Hostname: "ws.example.com", TLSName: "ws.example.com", HTTPHost: "ws.example.com", OriginAddress: "127.0.0.1", OriginPort: 11081, XrayVersion: "v26.3.27", Credentials: websocket},
		Hysteria2:     Hysteria2ViewRequest{Revision: 1, Enabled: true, DestinationIP: "192.0.2.10", Port: 443, ServerName: "direct.example.com", CertificateID: "qualification", MasqueradeResponse: "Not Found\n", CertificatePointer: "/var/lib/sbxr/certificates/domain/current", SingBoxVersion: "1.13.16", Credentials: hysteria2, DirectTLS: directTLS},
		TUIC:          TUICViewRequest{Revision: 1, Enabled: true, DestinationIP: "192.0.2.10", Port: 8443, ServerName: "direct.example.com", CertificateID: "qualification", CertificatePointer: "/var/lib/sbxr/certificates/domain/current", SingBoxVersion: "1.13.16", CongestionControl: state.CongestionCubic, Credentials: tuic, DirectTLS: directTLS},
		AnyTLS:        AnyTLSViewRequest{Revision: 1, Enabled: true, DestinationIP: "192.0.2.10", Port: 9443, ServerName: "direct.example.com", CertificateID: "qualification", CertificatePointer: "/var/lib/sbxr/certificates/domain/current", MinimumSingBoxVersion: "1.12.0", SingBoxVersion: "1.13.16", UseCorePadding: true, Credentials: anyTLS, DirectTLS: directTLS},
	}
	xrayConfiguration, singBoxConfiguration, _ := registryConfigurations(request)
	if len(xrayConfiguration) == 0 || len(singBoxConfiguration) == 0 {
		return QualificationFixture{}, errors.New("qualification configurations unavailable")
	}
	access := map[state.ClientAccessValue]string{}
	for _, value := range []string{"11111111-1111-4111-8111-111111111111", "0123456789abcdef", "22222222-2222-4222-8222-222222222222", "/2222222222222222222222222222222222222222222222222222222222222222", "33333333-3333-4333-8333-333333333333", "/3333333333333333333333333333333333333333333333333333333333333333", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "55555555-5555-4555-8555-555555555555", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"} {
		access[state.NewClientAccessValue(value)] = value
	}
	return QualificationFixture{xray: xrayConfiguration, singBox: singBoxConfiguration, source: registryPublication(request), access: access}, nil
}
