package subscriptionpublication

import (
	"context"
	"errors"
	"io"

	"github.com/albertloky/SBXR/internal/connectionprofiles"
)

type qualificationMihomoValidator struct{}

func (qualificationMihomoValidator) ValidateMihomo(context.Context, io.Reader) error { return nil }

type qualificationSingBoxValidator struct{}

func (qualificationSingBoxValidator) ValidateSingBox(context.Context, io.Reader) error { return nil }

// QualificationArtifacts returns public fixtures generated by the complete
// subscription renderer. Values are fixed test material, never Owner values.
func QualificationArtifacts() (map[string][]byte, error) {
	fixture, err := connectionprofiles.NewQualificationFixture()
	if err != nil {
		return nil, err
	}
	artifacts, err := New(qualificationMihomoValidator{}, qualificationSingBoxValidator{}).Render(context.Background(), fixture.PublicationSource(), fixture)
	if err != nil {
		return nil, err
	}
	result := map[string][]byte{}
	result["xray.json"], result["sing-box.json"] = fixture.Configurations()
	for name, identity := range map[string]RepresentationIdentity{"subscription-raw.txt": RawRepresentation, "subscription-base64.txt": Base64Representation, "subscription-v2rayn.txt": V2RayNRepresentation, "subscription-shadowrocket.txt": ShadowrocketRepresentation, "subscription-karing.json": KaringRepresentation, "subscription-mihomo.yaml": MihomoRepresentation, "subscription-sing-box.json": SingBoxRepresentation} {
		body, ok := artifacts.RepresentationBody(identity)
		if !ok || len(body) == 0 {
			return nil, errors.New("qualification representation unavailable")
		}
		result[name] = body
	}
	return result, nil
}
