#!/usr/bin/env python3
"""Add or remove scenario 18's one exact qualification-owned INPUT rule."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import ipaddress
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys


COMMENT = "sbxr-qualification-identity-unavailable"
STATE = Path("/run/sbxr-qualification/identity-unavailable-firewall.json")
IPTABLES = "/usr/sbin/iptables"
IPTABLES_SAVE = "/usr/sbin/iptables-save"


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="microseconds").replace("+00:00", "Z")


def run(command: list[str], check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, check=check, text=True, stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE)


def rule_arguments(ipv4: str) -> list[str]:
    return ["-d", ipv4 + "/32", "-p", "tcp", "--dport", "8443", "-m", "comment",
            "--comment", COMMENT, "-j", "REJECT", "--reject-with", "tcp-reset"]


def expected_saved_rule(ipv4: str) -> list[str]:
    return ["-A", "INPUT", "-d", ipv4 + "/32", "-p", "tcp", "-m", "tcp",
            "--dport", "8443", "-m", "comment", "--comment", COMMENT, "-j",
            "REJECT", "--reject-with", "tcp-reset"]


def rules(command=run) -> str:
    return command([IPTABLES_SAVE, "-t", "filter"], True).stdout


def qualification_rules(body: str) -> list[list[str]]:
    found = []
    for line in body.splitlines():
        try:
            words = shlex.split(line)
        except ValueError:
            if COMMENT in line:
                found.append(["malformed", line])
            continue
        if COMMENT in words:
            found.append(words)
    return found


def canonical_rules(body: str) -> str:
    """Remove only iptables-save timestamps and volatile chain counters."""
    result = []
    for line in body.splitlines():
        if line.startswith("# Generated by iptables-save ") or line.startswith("# Completed on "):
            continue
        match = re.fullmatch(r"(:\S+\s+\S+)\s+\[\d+:\d+\]", line)
        result.append(match.group(1) + " [0:0]" if match else line)
    return "\n".join(result) + "\n"


def write_state(document: dict, before: str) -> None:
    STATE.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    descriptor = os.open(STATE, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        payload = json.dumps({**document, "before": before}, sort_keys=True) + "\n"
        os.write(descriptor, payload.encode())
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def read_state() -> dict:
    descriptor = os.open(STATE, os.O_RDONLY | os.O_NOFOLLOW)
    try:
        return json.loads(os.read(descriptor, 1 << 20))
    finally:
        os.close(descriptor)


def add(ipv4: str, command=run) -> dict:
    ipv4 = str(ipaddress.IPv4Address(ipv4))
    before = rules(command)
    if STATE.exists() or qualification_rules(before):
        raise RuntimeError("qualification firewall state is not clean")
    before_canonical = canonical_rules(before)
    document = {"schema": "sbxr-v4-firewall-control-v1", "ipv4": ipv4,
                "before_sha256": hashlib.sha256(before_canonical.encode()).hexdigest()}
    write_state(document, before_canonical)
    try:
        command([IPTABLES, "-w", "-I", "INPUT", "1", *rule_arguments(ipv4)], True)
        after = rules(command)
        if qualification_rules(after) != [expected_saved_rule(ipv4)]:
            raise RuntimeError("exact qualification rule was not installed once")
        return {**document, "installed": True, "qualification_rule_count": 1,
                "installed_at": now()}
    except Exception:
        command([IPTABLES, "-w", "-D", "INPUT", *rule_arguments(ipv4)], False)
        try:
            if canonical_rules(rules(command)) == before_canonical:
                STATE.unlink()
        except Exception:
            pass
        raise


def remove(command=run) -> dict:
    if not STATE.is_file():
        raise RuntimeError("qualification firewall state is absent")
    document = read_state()
    ipv4 = document.get("ipv4", "")
    if document.get("schema") != "sbxr-v4-firewall-control-v1" or qualification_rules(rules(command)) != [expected_saved_rule(ipv4)]:
        raise RuntimeError("qualification firewall rule drifted")
    command([IPTABLES, "-w", "-D", "INPUT", *rule_arguments(ipv4)], True)
    after = rules(command)
    after_canonical = canonical_rules(after)
    if qualification_rules(after) or after_canonical != document.get("before"):
        raise RuntimeError("original firewall state was not restored")
    STATE.unlink()
    return {"schema": document["schema"], "ipv4": ipv4, "restored": True,
            "qualification_rule_count": 0, "original_filter_sha256": document["before_sha256"],
            "after_sha256": hashlib.sha256(after_canonical.encode()).hexdigest(), "restored_at": now()}


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="operation", required=True)
    add_parser = subparsers.add_parser("add")
    add_parser.add_argument("ipv4")
    subparsers.add_parser("remove")
    options = parser.parse_args(arguments)
    if sys.platform != "linux" or os.geteuid() != 0:
        parser.error("root on Linux is required")
    result = add(options.ipv4) if options.operation == "add" else remove()
    print(json.dumps(result, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
