import fcntl
import importlib.util
import json
import multiprocessing
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest import mock


ROOT = Path(__file__).parent


def load(name, filename):
    spec = importlib.util.spec_from_file_location(name, ROOT / filename)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


route = load("route_control", "route-control.py")
firewall = load("firewall_control", "firewall-control.py")
directory = load("directory_locks", "directory-locks.py")


class FakeSystemd:
    def __init__(self):
        self.timer_enabled = "enabled"
        self.timer_active = "active"
        self.service_active = "inactive"
        self.service_marker = "unchanged"
        self.commands = []

    def __call__(self, command, check=True):
        self.commands.append(command)
        if command[:2] == ["systemctl", "is-enabled"]:
            value = self.timer_enabled
        elif command[:2] == ["systemctl", "is-active"]:
            value = self.service_active if command[2] == route.SERVICE else self.timer_active
        elif command[:2] == ["systemctl", "show"]:
            value = "no" if command[2] == "--property=Persistent" else self.service_marker
        elif command[:2] == ["systemctl", "stop"]:
            self.timer_active = "inactive"
            value = ""
        elif command[:2] == ["systemctl", "start"]:
            self.timer_active = "active"
            value = ""
        elif command[:2] == ["systemctl", "enable"]:
            self.timer_enabled = "enabled"
            value = ""
        elif command[:2] == ["systemctl", "disable"]:
            self.timer_enabled = "disabled"
            value = ""
        elif command[:2] == ["systemctl", "daemon-reload"]:
            value = ""
        else:
            raise AssertionError(command)
        return subprocess.CompletedProcess(command, 0, value, "")


class FakeFirewall:
    def __init__(self, ipv4):
        self.ipv4 = ipv4
        self.base = "# Generated by iptables-save v1.8.10 on Tue\n*filter\n:INPUT ACCEPT [7:700]\nCOMMIT\n# Completed on Tue\n"
        self.installed = False

    def __call__(self, command, check=True):
        if command == [firewall.IPTABLES_SAVE, "-t", "filter"]:
            line = ('-A INPUT -d %s/32 -p tcp -m tcp --dport 8443 -m comment '
                    '--comment "%s" -j REJECT --reject-with tcp-reset\n' %
                    (self.ipv4, firewall.COMMENT)) if self.installed else ""
            body = self.base.replace("COMMIT\n", line + "COMMIT\n")
            return subprocess.CompletedProcess(command, 0, body, "")
        if command[:5] == [firewall.IPTABLES, "-w", "-I", "INPUT", "1"]:
            self.installed = True
            return subprocess.CompletedProcess(command, 0, "", "")
        if command[:4] == [firewall.IPTABLES, "-w", "-D", "INPUT"]:
            self.installed = False
            return subprocess.CompletedProcess(command, 0, "", "")
        raise AssertionError(command)


def hold_directory_locks(paths, owner_uid, connection):
    locks = directory.DirectoryLocks(paths, owner_uid)
    try:
        connection.send(locks.acquire())
        connection.recv()
        locks.revalidate()
        locks.release()
        connection.send("released")
    except Exception as error:
        connection.send(type(error).__name__)
    finally:
        connection.close()


class ControlTest(unittest.TestCase):
    def test_route_control_restores_same_inode_bytes_and_timer_state(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            unit = root / "snap.certbot.renew.service"
            hidden = root / "snap.certbot.renew.service.hidden"
            state = root / "state.json"
            unit.write_text("[Service]\nExecStart=/real/route\n")
            unit.chmod(0o644)
            before = unit.stat()
            systemd = FakeSystemd()
            real_identity = route.identity
            with mock.patch.object(route, "UNIT", unit), mock.patch.object(route, "HIDDEN", hidden), \
                    mock.patch.object(route, "STATE", state), mock.patch.object(
                        route, "identity", side_effect=lambda path: real_identity(path, os.getuid())):
                route.inject(systemd)
                self.assertFalse(unit.exists())
                self.assertTrue(hidden.exists())
                self.assertEqual(systemd.timer_active, "inactive")
                result = route.restore(systemd)
            after = unit.stat()
            self.assertTrue(result["restored"])
            self.assertEqual((before.st_dev, before.st_ino), (after.st_dev, after.st_ino))
            self.assertEqual(unit.read_text(), "[Service]\nExecStart=/real/route\n")
            self.assertEqual((systemd.timer_enabled, systemd.timer_active), ("enabled", "active"))
            self.assertFalse(state.exists())
            self.assertNotIn(["systemctl", "start", route.SERVICE], systemd.commands)

    def test_route_control_refuses_active_service_before_mutation(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            unit = root / "snap.certbot.renew.service"
            hidden = root / "hidden"
            state = root / "state.json"
            unit.write_text("unit")
            unit.chmod(0o644)
            systemd = FakeSystemd()
            systemd.service_active = "active"
            real_identity = route.identity
            with mock.patch.object(route, "UNIT", unit), mock.patch.object(route, "HIDDEN", hidden), \
                    mock.patch.object(route, "STATE", state), mock.patch.object(
                        route, "identity", side_effect=lambda path: real_identity(path, os.getuid())):
                with self.assertRaisesRegex(RuntimeError, "service is active"):
                    route.inject(systemd)
            self.assertTrue(unit.exists())
            self.assertFalse(hidden.exists())
            self.assertFalse(state.exists())

    def test_firewall_control_adds_once_and_requires_exact_restore(self):
        with tempfile.TemporaryDirectory() as folder:
            state = Path(folder) / "state.json"
            fake = FakeFirewall("203.0.113.7")
            with mock.patch.object(firewall, "STATE", state):
                added = firewall.add("203.0.113.7", fake)
                self.assertTrue(added["installed"])
                self.assertTrue(fake.installed)
                restored = firewall.remove(fake)
            self.assertTrue(restored["restored"])
            self.assertFalse(fake.installed)
            self.assertFalse(state.exists())

    def test_firewall_control_detects_unrelated_drift_during_restore(self):
        with tempfile.TemporaryDirectory() as folder:
            state = Path(folder) / "state.json"
            fake = FakeFirewall("203.0.113.7")
            with mock.patch.object(firewall, "STATE", state):
                firewall.add("203.0.113.7", fake)
                fake.base = "# Generated by iptables-save v1.8.10 on Wed\n*filter\n:INPUT ACCEPT [9:900]\n-A INPUT -s 192.0.2.1/32 -j ACCEPT\nCOMMIT\n# Completed on Wed\n"
                with self.assertRaisesRegex(RuntimeError, "original firewall state"):
                    firewall.remove(fake)
            self.assertFalse(fake.installed)
            self.assertTrue(state.exists())

    def test_firewall_canonicalization_ignores_only_timestamps_and_chain_counters(self):
        first = "# Generated by iptables-save v1 on A\n*filter\n:INPUT ACCEPT [1:2]\n-A INPUT -s 192.0.2.1/32 -j ACCEPT\nCOMMIT\n# Completed on A\n"
        second = "# Generated by iptables-save v1 on B\n*filter\n:INPUT ACCEPT [9:99]\n-A INPUT -s 192.0.2.1/32 -j ACCEPT\nCOMMIT\n# Completed on B\n"
        changed = second.replace("192.0.2.1", "192.0.2.2")
        self.assertEqual(firewall.canonical_rules(first), firewall.canonical_rules(second))
        self.assertNotEqual(firewall.canonical_rules(first), firewall.canonical_rules(changed))

    def test_directory_locks_contend_in_certbot_posix_domain_and_release(self):
        with tempfile.TemporaryDirectory() as folder:
            paths = []
            for name in ("etc", "lib", "log"):
                path = Path(folder) / name
                path.write_text("")
                path.chmod(0o600)
                paths.append(str(path))
            parent, child = multiprocessing.Pipe()
            process = multiprocessing.Process(target=hold_directory_locks,
                                                args=(paths, os.getuid(), child))
            process.start()
            acquired = parent.recv()
            self.assertEqual(len(acquired), 3)
            descriptors = [os.open(path, os.O_RDWR) for path in paths]
            try:
                for descriptor in descriptors:
                    with self.assertRaises(BlockingIOError):
                        fcntl.lockf(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
                parent.send("release")
                self.assertEqual(parent.recv(), "released")
                for descriptor in descriptors:
                    fcntl.lockf(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
                    fcntl.lockf(descriptor, fcntl.LOCK_UN)
            finally:
                for descriptor in descriptors:
                    os.close(descriptor)
                process.join(5)
            self.assertEqual(process.exitcode, 0)

    def test_directory_locks_reject_symlink(self):
        with tempfile.TemporaryDirectory() as folder:
            target = Path(folder) / "target"
            target.write_text("")
            link = Path(folder) / "link"
            link.symlink_to(target)
            locks = directory.DirectoryLocks([str(link)], os.getuid())
            with self.assertRaisesRegex(RuntimeError, "unsafe Certbot lock"):
                locks.acquire()

    def test_directory_locks_create_and_restore_initial_absence(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / "absent-lock"
            locks = directory.DirectoryLocks([str(path)], os.getuid())
            acquired = locks.acquire()
            self.assertTrue(acquired[0]["created"])
            self.assertTrue(path.is_file())
            locks.revalidate()
            locks.release()
            self.assertFalse(path.exists())

    def test_directory_locks_close_untracked_descriptor_when_metadata_fails(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / "lock"
            path.write_text("")
            path.chmod(0o600)
            locks = directory.DirectoryLocks([str(path)], os.getuid())
            opened = []
            real_open = directory.os.open

            def capture_open(*args, **kwargs):
                descriptor = real_open(*args, **kwargs)
                opened.append(descriptor)
                return descriptor

            with mock.patch.object(directory.os, "open", side_effect=capture_open), \
                    mock.patch.object(locks, "metadata", side_effect=OSError("hash failed")):
                with self.assertRaisesRegex(OSError, "hash failed"):
                    locks.acquire()
            self.assertEqual(len(opened), 1)
            with self.assertRaises(OSError):
                os.fstat(opened[0])
            self.assertEqual(locks.descriptors, [])

    def test_directory_locks_revalidate_metadata_and_body(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / "lock"
            path.write_text("before")
            path.chmod(0o600)
            locks = directory.DirectoryLocks([str(path)], os.getuid())
            locks.acquire()
            path.write_text("after!")
            with self.assertRaisesRegex(RuntimeError, "held Certbot lock identity changed"):
                locks.revalidate()
            locks.release()


if __name__ == "__main__":
    unittest.main()
